#include <cstdint>
#include <vector>
#include <string>
#include "goemon_debug.h"

std::vector<goemon64::AreaWarps> goemon64::game_warps {
    { "Oedo Castle", {
        { 0x000, "Oedo Castle 1F Tile Room", { "Entrance" } },
        { 0x001, "Oedo Castle Tile Room - Unused", { "Entrance" } },
        { 0x002, "Oedo Castle 1F Entrance", { "Entrance" } },
        { 0x003, "Oedo Castle 1F Swatting Robot Silver Key Room", { "Entrance" } },
        { 0x004, "Oedo Castle 1F Gold Dango Room", { "Entrance" } },
        { 0x005, "Oedo Castle 1F Chain Pipe Fork", { "Entrance" } },
        { 0x006, "Oedo Castle 1F Congo's Feet", { "Entrance" } },
        { 0x007, "Oedo Castle 1F Chain Pipe Key Room", { "Entrance" } },
        { 0x008, "Oedo Castle 1F Swatting Robot Gold Key Room", { "Entrance" } },
        { 0x009, "Oedo Castle 1F Turtle Pad Room", { "Entrance" } },
        { 0x00a, "Oedo Castle 2F Crusher Key Room", { "Entrance" } },
        { 0x00b, "Oedo Castle 2F Silver Cat Room", { "Entrance" } },
        { 0x00c, "Oedo Castle 1F-2F Elevator / Dango Spawner Room", { "Entrance" } },
        { 0x00d, "Oedo Castle 2F Spike Chain Room", { "Entrance" } },
        { 0x00e, "Oedo Castle 2F Dango Ninja Room", { "Entrance" } },
        { 0x00f, "Oedo Castle 2F Congo's Chest", { "Entrance" } },
        { 0x010, "Oedo Castle 2F Crusher Platforms", { "Entrance" } },
        { 0x011, "Oedo Castle 2F Chain Pipe Moat", { "Entrance" } },
        { 0x012, "Oedo Castle 2F Silver Key Room", { "Entrance" } },
        { 0x013, "Oedo Castle Gold Key Room - Unused", { "Entrance" } },
        { 0x014, "Oedo Castle 2F Congo's Hand", { "Entrance" } },
        { 0x015, "Oedo Castle 2F Blocked Silver Cat Room", { "Entrance" } },
        { 0x016, "Oedo Castle 2F Congo Boss Room", { "Entrance" } },
        { 0x017, "Congo Boss Room - Unused", { "Entrance" } },
        { 0x01a, "Oedo Castle 2F-3F Elevator / Baron Room", { "Entrance" } },
        { 0x01c, "Oedo Castle Final Room - Unused", { "Entrance" } },
        { 0x028, "Oedo Castle Lord's Room", { "Entrance" } },
        { 0x056, "Oedo Castle 1st Elevator Room - Unused", { "Entrance" } },
    }},
    { "Ghost Toys Castle", {
        { 0x02f, "Ghost Toys Entrance", { "Entrance" } },
        { 0x030, "Ghost Toys 1F Elevator Shogi Room", { "Entrance" } },
        { 0x031, "Ghost Toys 1F Crane Room", { "Entrance" } },
        { 0x032, "Ghost Toys 1F Spike Room", { "Entrance" } },
        { 0x033, "Ghost Toys 1F Cannon Room", { "Entrance" } },
        { 0x034, "Ghost Toys 1F Spike Cannon Boat Room", { "Entrance" } },
        { 0x035, "Ghost Toys 1F Flower Blooming Key Room", { "Entrance" } },
        { 0x036, "Ghost Toys 1F Shogi Cannon Gold Cat Room", { "Entrance" } },
        { 0x039, "Ghost Toys 1F Invisible Ghost Room", { "Entrance" } },
        { 0x03a, "Ghost Toys 1F Spike Darumanyo Room", { "Entrance" } },
        { 0x03b, "Ghost Toys 1F Invisible Ghost Key Room", { "Entrance" } },
        { 0x03c, "Ghost Toys 1F-2F Elevator / Tiny Darumanyo Room", { "Entrance" } },
        { 0x03e, "Ghost Toys 2F Spinning Top Key Room", { "Entrance" } },
        { 0x03f, "Ghost Toys 2F Big Spinning Spike Chain Room", { "Entrance" } },
        { 0x040, "Ghost Toys 2F Invisible Darumanyo Key Room", { "Entrance" } },
        { 0x041, "Ghost Toys 2F Jump Rope Room", { "Entrance" } },
        { 0x042, "Ghost Toys 2F Treasure Room", { "Entrance" } },
        { 0x043, "Ghost Toys 2F False Floor Gold Key Room", { "Entrance" } },
        { 0x044, "Ghost Toys 2F Darumanyo Diamond Lock Room", { "Entrance" } },
        { 0x045, "Ghost Toys 2F Billiards Room", { "Entrance" } },
        { 0x046, "Ghost Toys 2F Spike Cannon Diamond Key Room", { "Entrance" } },
        { 0x049, "Ghost Toys 2F-3F Elevator / Darumanyo Boss Room", { "Entrance" } },
    }},
    { "Festival Temple", {
        { 0x05a, "Festival Temple West Main Entrance", { "Entrance" } },
        { 0x05b, "Festival Temple West Gold Cat Dango Room", { "Entrance" } },
        { 0x05c, "Festival Temple West Hot Platform Drummer Fox Room", { "Entrance" } },
        { 0x05d, "Festival Temple West Hot Platform Samurai Room", { "Entrance" } },
        { 0x05e, "Festival Temple West Hot Platform Gold Key Room", { "Entrance" } },
        { 0x05f, "Festival Temple West Spike Chain Elly Fant Room", { "Entrance" } },
        { 0x060, "Festival Temple East Tank Hallway", { "Entrance" } },
        { 0x061, "Festival Temple East Chain Pipe Room", { "Entrance" } },
        { 0x062, "Festival Temple East Meatsaw Hammer Room", { "Entrance" } },
        { 0x063, "Festival Temple East Samurai Barrel Arrow Room", { "Entrance" } },
        { 0x064, "Festival Temple East Drum Room", { "Entrance" } },
        { 0x065, "Festival Temple East Samurai Bomb Room", { "Entrance" } },
        { 0x066, "Festival Temple East Bamboo Barrel Bomb Room", { "Entrance" } },
        { 0x067, "Festival Temple East Silver Cat Lock Fork", { "Entrance" } },
        { 0x068, "Festival Temple Central Gold Lock Room", { "Entrance" } },
        { 0x069, "Festival Temple Central Fox Tank Hallway", { "Entrance" } },
        { 0x06a, "Festival Temple Central Samurai Tank Room", { "Entrance" } },
        { 0x06b, "Festival Temple Central Accordion Room", { "Entrance" } },
        { 0x06c, "Festival Temple Central Ring Key Hallway", { "Entrance" } },
        { 0x06d, "Festival Temple Central Samurai Platform Room", { "Entrance" } },
        { 0x06e, "Festival Temple East Ice Kunai Room", { "Entrance" } },
        { 0x06f, "Festival Temple North Fish Kite Waterfall Column", { "Entrance" } },
        { 0x070, "Festival Temple North Bamboo Path to Boss", { "Entrance" } },
        { 0x071, "Festival Temple North Tsurami Boss Room", { "Entrance" } },
    }},
    { "Gourmet Submarine", {
        { 0x080, "Submarine Bazooka Room - Unused", { "Entrance" } },
        { 0x081, "Gourmet Sub 2F Bazooka Room", { "Entrance" } },
        { 0x082, "Gourmet Sub 2F Jetpack Crab Gold Key & Double Lock Room", { "Entrance" } },
        { 0x083, "Gourmet Sub 2F Seahorse / Mini Ebisumaru Crosspath", { "Entrance" } },
        { 0x084, "Submarine Unknown Room - Unused", { "Entrance" } },
        { 0x085, "Gourmet Sub 2F Lava Treadmill Key & Lock Room", { "Entrance" } },
        { 0x086, "Gourmet Sub 2F Turret Dango Stockpile Room", { "Entrance" } },
        { 0x087, "Gourmet Sub 2F Ramen Soup Corridor", { "Entrance" } },
        { 0x088, "Submarine Red Ramen Corridor - Unused", { "Entrance" } },
        { 0x089, "Gourmet Sub 2F Underwater Spiny Key & Lock Room", { "Entrance" } },
        { 0x08a, "Gourmet Sub 3F-4F Elevator / Turret Tightrope Room", { "Entrance" } },
        { 0x08b, "Gourmet Sub 3F Invisible Path Diamond Key Room", { "Entrance" } },
        { 0x08c, "Gourmet Sub 3F Fox Ramen Platforms & Diamond Lock Fork", { "Entrance" } },
        { 0x08d, "Gourmet Sub 3F Treasure Room", { "Entrance" } },
        { 0x08e, "Gourmet Sub 3F Sword Robot Key Room", { "Entrance" } },
        { 0x090, "Gourmet Sub 3F Blaster Crab Room", { "Entrance" } },
        { 0x091, "Gourmet Sub 1F-3F Entrance / Elevator", { "Entrance" } },
        { 0x094, "Gourmet Sub 3F Sushi Belt Silver Key Room", { "Entrance" } },
        { 0x095, "Gourmet Sub 3F Chain Pipe Lava Room", { "Entrance" } },
        { 0x096, "Gourmet Sub 3F Chain Pipe Avoidance Room", { "Entrance" } },
        { 0x097, "Gourmet Sub 3F Chain Pipe Ice Kunai Combination Room", { "Entrance" } },
        { 0x098, "Gourmet Sub 2F-3F Ramen Soup Arrow Room", { "Entrance" } },
        { 0x099, "Gourmet Sub 3F Floating Tofu Silver Lock Room", { "Entrance" } },
        { 0x09d, "Gourmet Sub 4F Thaisamba Boss Room", { "Entrance" } },
    }},
    { "Musical Castle", {
        { 0x0a8, "Musical Castle 1 Entrance", { "Entrance" } },
        { 0x0a9, "Musical Castle 1 Flame Dango Ryo Room", { "Entrance" } },
        { 0x0aa, "Musical Castle 1 Tall Key & Lock Room", { "Entrance" } },
        { 0x0ab, "Musical Castle 1 Straight Slicer Room", { "Entrance" } },
        { 0x0ac, "Musical Castle 1 Triple Slicer Room", { "Entrance" } },
        { 0x0ad, "Musical Castle 1 Gold Key Fan Room", { "Entrance" } },
        { 0x0ae, "Musical Castle 1 High Jump Gold Key Waves Room", { "Entrance" } },
        { 0x0af, "Musical Castle 1 Drum Jump Waves Room", { "Entrance" } },
        { 0x0b0, "Musical Castle 1 Gold Lock Fan Room", { "Entrance" } },
        { 0x0b1, "Musical Castle 1 Waves Turret Connecting Room", { "Entrance" } },
        { 0x0b2, "Musical Castle 1 Multi-Lock 3-Way Fork", { "Entrance" } },
        { 0x0b3, "Musical Castle 1 B1F Hammer Thrower Room", { "Entrance" } },
        { 0x0b4, "Musical Castle 1 B1F Rotating Cube Diamond Key Room", { "Entrance" } },
        { 0x0b5, "Musical Castle 1 Mini Gold Key Big Wave Generator Room", { "Entrance" } },
        { 0x0b6, "Musical Castle 1 Big Aquarium Room", { "Entrance" } },
        { 0x0b7, "Sogen Hedge Maze", { "Entrance" } },
        { 0x0b8, "Musical Castle 2 Entrance", { "Entrance" } },
        { 0x0b9, "Musical Castle 2 Beyond Entrance Platforms Room", { "Entrance" } },
        { 0x0ba, "Musical Castle 2 Left Entrance Treadmill Room", { "Entrance" } },
        { 0x0bb, "Musical Castle 2 Metal Box Lava Room", { "Entrance" } },
        { 0x0bc, "Musical Castle 2 Gold Cat Hallway", { "Entrance" } },
        { 0x0bd, "Musical Castle 2 Diamond Key Platform Elevator", { "Entrance" } },
        { 0x0be, "Musical Castle 2 Right Entrance Slope Room", { "Entrance" } },
        { 0x0bf, "Musical Castle 2 B1F Descent", { "Entrance" } },
        { 0x0c0, "Musical Castle 2 B1F Kaleidoscope Room", { "Entrance" } },
        { 0x0c1, "Musical Castle 2 B1F Gorgeous Stage", { "Entrance" } },
    }},
    { "Overworld", {
        { 0x12c, "Kai Highway", { "Entrance" } },
        { 0x12d, "Mt. Fuji", { "Entrance" } },
        { 0x12e, "Mt. Fuji Interior (Base)", { "Entrance" } },
        { 0x12f, "Mt. Fuji Interior (Summit)", { "Entrance" } },
        { 0x131, "Musashi-Iga Tunnel", { "Entrance" } },
        { 0x132, "Iga", { "Entrance" } },
        { 0x133, "Yamato", { "Entrance" } },
        { 0x134, "Yamato Shrine", { "Entrance" } },
        { 0x135, "Yamato - Underwater Cave", { "Entrance" } },
        { 0x136, "Yamato - Bamboo Forest", { "Entrance" } },
        { 0x137, "Yamato - Turtle Rock", { "Entrance" } },
        { 0x138, "Kii-Awaji Island", { "Entrance" } },
        { 0x139, "Kii-Awaji - Husband and Wife Rocks", { "Entrance" } },
        { 0x13a, "Tosa", { "Entrance" } },
        { 0x13b, "Tosa - Vine Bridge", { "Entrance" } },
        { 0x13c, "Kompira Mountain 1st Block", { "Entrance" } },
        { 0x13d, "Kompira Mountain 2nd Block", { "Entrance" } },
        { 0x13e, "Kompira Mountain 3rd Block", { "Entrance" } },
        { 0x13f, "Kompira Mountain 4th Block", { "Entrance" } },
        { 0x140, "Kompira Shrine", { "Entrance" } },
        { 0x141, "Iyo", { "Entrance" } },
        { 0x142, "Iyo - Hot Springs", { "Entrance" } },
        { 0x143, "Bizen", { "Entrance" } },
        { 0x144, "Aki - Nagato", { "Entrance" } },
        { 0x145, "Hagi", { "Entrance" } },
        { 0x146, "Akiyoshidai", { "Entrance" } },
        { 0x147, "Shuhodo Tunnel to Festival Temple", { "Entrance" } },
        { 0x148, "Izumo", { "Entrance" } },
        { 0x149, "Izumo - Big Tree", { "Entrance" } },
        { 0x14a, "Inaba", { "Entrance" } },
        { 0x14b, "Mutsu - Mt. Fear", { "Entrance" } },
        { 0x14c, "Ugo - Stone Circle", { "Entrance" } },
        { 0x14d, "Mutsu - Shoreline", { "Entrance" } },
        { 0x14e, "Japan Sea - Underwater", { "Entrance" } },
        { 0x14f, "Northeast Tunnel to Festival Village 1", { "Entrance" } },
        { 0x150, "Northeast Tunnel to Festival Village 2", { "Entrance" } },
        { 0x151, "Mutsu - Path to Festival Village", { "Entrance" } },
        { 0x152, "Mutsu - Uzen Tunnel", { "Entrance" } },
        { 0x153, "Kanmonkyo Gateway Viewpoint", { "Entrance" } },
        { 0x154, "Waterfall of Kegon", { "Entrance" } },
        { 0x155, "Dragon Fight", { "Entrance" } },
        { 0x157, "Mermaid Waterfall - Unused", { "Entrance" } },
        { 0x15a, "Kompira Shrine - Unused", { "Entrance" } },
        { 0x15b, "Lake Tree - Unused", { "Entrance" } },
        { 0x15e, "Oedo - Bridge to Musashi", { "Entrance" } },
        { 0x162, "Oedo - Bridge to Oedo Castle", { "Entrance" } },
        { 0x164, "Path to Oedo Castle (Chain Pipe)", { "Entrance" } },
        { 0x165, "Stairway to Oedo Castle", { "Entrance" } },
        { 0x166, "Outside Oedo Castle", { "Entrance" } },
    }},
    { "Towns", {
        { 0x130, "Musashi", { "Entrance" } },
        { 0x15f, "Oedo Town (West)", { "Entrance" } },
        { 0x160, "Oedo Town (North)", { "Entrance" } },
        { 0x161, "Oedo Town (South)", { "Entrance" } },
        { 0x163, "Oedo Town (Northwest)", { "Entrance" } },
        { 0x167, "Zazen - Gate", { "Entrance" } },
        { 0x168, "Zazen - Entrance Bridge", { "Entrance" } },
        { 0x169, "Zazen Town (South)", { "Entrance" } },
        { 0x16a, "Zazen - Kappa Pond", { "Entrance" } },
        { 0x16b, "Zazen - Waterway", { "Entrance" } },
        { 0x16c, "Zazen Town (North)", { "Entrance" } },
        { 0x16d, "Zazen - Golden Temple", { "Entrance" } },
        { 0x16e, "Zazen - Bridge to Bizen", { "Entrance" } },
        { 0x16f, "Zazen - Path to Mt. Nyoigatake", { "Entrance" } },
        { 0x170, "Zazen - Mt. Nyoigatake", { "Entrance" } },
        { 0x171, "Zazen - Bridge to Yamato (Benkei)", { "Entrance" } },
        { 0x172, "Zazen - Waterfall", { "Entrance" } },
        { 0x173, "Zazen - Ushiwaka", { "Entrance" } },
        { 0x175, "Folkypoke Village (East)", { "Entrance" } },
        { 0x176, "Folkypoke Village (South)", { "Entrance" } },
        { 0x177, "Folkypoke Village (West)", { "Entrance" } },
        { 0x178, "Folkypoke Village (Northeast)", { "Entrance" } },
        { 0x179, "Festival Village (West)", { "Entrance" } },
        { 0x17a, "Festival Village (East)", { "Entrance" } },
        { 0x17b, "Festival Village - Festival Square", { "Entrance" } },
        { 0x17c, "Festival Village (Northwest)", { "Entrance" } },
        { 0x17d, "Festival Village - Hidden Lake Area", { "Entrance" } },
        { 0x180, "Zazen Waterway - Unused", { "Entrance" } },
    }},
    { "Shops & Restaurants", {
        { 0x190, "Oedo - Restaurant", { "Entrance" } },
        { 0x191, "Zazen - Restaurant", { "Entrance" } },
        { 0x192, "Folkypoke - Restaurant", { "Entrance" } },
        { 0x193, "Festival Village - Restaurant", { "Entrance" } },
        { 0x194, "Sogen - Restaurant", { "Entrance" } },
        { 0x195, "Unknown Town Restaurant - Unused", { "Entrance" } },
        { 0x196, "Oedo - Riceball Shop", { "Entrance" } },
        { 0x197, "Oedo - Armor Shop", { "Entrance" } },
        { 0x198, "Zazen - Riceball Shop", { "Entrance" } },
        { 0x199, "Zazen - Armor Shop", { "Entrance" } },
        { 0x19a, "Folkypoke - Riceball Shop", { "Entrance" } },
        { 0x19b, "Folkypoke - Armor Shop", { "Entrance" } },
        { 0x19c, "Festival Village - Shop", { "Entrance" } },
        { 0x19d, "Festival Village - Hidden Lake Shop", { "Entrance" } },
        { 0x19e, "Sogen - Riceball Shop", { "Entrance" } },
        { 0x19f, "Sogen - Armor Shop", { "Entrance" } },
        { 0x1a0, "Unknown Town Shop - Unused", { "Entrance" } },
        { 0x1a1, "Oedo - Inn", { "Entrance" } },
        { 0x1a2, "Zazen - Inn", { "Entrance" } },
        { 0x1a3, "Folkypoke - Inn", { "Entrance" } },
        { 0x1a4, "Festival Village - Inn", { "Entrance" } },
        { 0x1a5, "Sogen - Inn", { "Entrance" } },
        { 0x1a6, "Unknown Town Inn - Unused", { "Entrance" } },
        { 0x1a7, "Oedo - Plasma", { "Entrance" } },
        { 0x1a8, "Zazen - Plasma", { "Entrance" } },
        { 0x1a9, "Folkypoke - Plasma", { "Entrance" } },
        { 0x1aa, "Festival Village - Plasma", { "Entrance" } },
        { 0x1ab, "Unknown Town Plasma - Unused", { "Entrance" } },
        { 0x1ac, "Unknown Town Plasma - Unused", { "Entrance" } },
        { 0x1ad, "Oedo Guardhouse", { "Entrance" } },
        { 0x1ae, "Zazen Guardhouse", { "Entrance" } },
    }},
    { "Teahouses & Tourism", {
        { 0x1b0, "Oedo - Omitsu's Teahouse", { "Entrance" } },
        { 0x1b1, "Kai Highway Teahouse", { "Entrance" } },
        { 0x1b2, "Awaji Island Coffee Shop - Unused", { "Entrance" } },
        { 0x1b3, "Kii-Awaji Teahouse", { "Entrance" } },
        { 0x1b4, "Kompira Teahouse", { "Entrance" } },
        { 0x1b5, "Iyo Teahouse", { "Entrance" } },
        { 0x1b6, "Izumo Teahouse", { "Entrance" } },
        { 0x1b8, "Folkypoke Tourism Center", { "Entrance" } },
        { 0x1b9, "Kii-Awaji Tourism Center", { "Entrance" } },
        { 0x1ba, "Unknown Town Guardhouse - Unused", { "Entrance" } },
    }},
    { "Houses", {
        { 0x1bb, "West Oedo House (Drunk)", { "Entrance" } },
        { 0x1bc, "North Oedo House (Boy)", { "Entrance" } },
        { 0x1bd, "North Oedo House (Red Woman)", { "Entrance" } },
        { 0x1be, "South Zazen House (Old Woman)", { "Entrance" } },
        { 0x1bf, "Kompira Shrine House", { "Entrance" } },
        { 0x1c0, "Unknown Town House - Unused", { "Entrance" } },
        { 0x1c1, "South Oedo House (Old Woman)", { "Entrance" } },
        { 0x1c2, "South Oedo House (Young Woman)", { "Entrance" } },
        { 0x1c3, "South Oedo House (Man c3)", { "Entrance" } },
        { 0x1c4, "South Oedo House (Muscle Training Gym, empty?)", { "Entrance" } },
        { 0x1c5, "South Oedo House (Man c5)", { "Entrance" } },
        { 0x1c6, "Folkypoke House (Boy)", { "Entrance" } },
        { 0x1c7, "Folkypoke House (Old Woman)", { "Entrance" } },
        { 0x1c8, "Folkypoke House (Drunk)", { "Entrance" } },
        { 0x1c9, "Folkypoke House (Red Woman)", { "Entrance" } },
        { 0x1ca, "East Festival House (Dog)", { "Entrance" } },
        { 0x1cb, "East Festival House (Red Woman)", { "Entrance" } },
        { 0x1cc, "East Festival House (Drunk)", { "Entrance" } },
        { 0x1cd, "Northwest Festival House (Old Man)", { "Entrance" } },
        { 0x1ce, "Unknown Training Gym - Unused", { "Entrance" } },
        { 0x1cf, "South Oedo House (Muscle Training Gym, occupied?)", { "Entrance" } },
        { 0x1d1, "South Oedo - Goemon's House", { "Entrance" } },
        { 0x1d2, "Mt. Fuji - Pipe Maker's House", { "Entrance" } },
        { 0x1d3, "Kompira Shrine Charm Shop", { "Entrance" } },
        { 0x1d4, "Mt. Fear - Witch's House", { "Entrance" } },
    }},
    { "Minigames", {
        { 0x1d0, "Sasuke Jetpack Training", { "Entrance" } },
        { 0x1e0, "Goemon Impact Minigame", { "Entrance" } },
        { 0x1e1, "Ebisumaru Sweets Minigame", { "Entrance" } },
        { 0x1e2, "Sasuke High Jump Minigame", { "Entrance" } },
    }},
};

