name: validate
on:
  workflow_call:
    inputs:
      SDL2_VERSION:
        type: string
        required: false
        default: '2.30.3'
      N64RECOMP_COMMIT:
        type: string
        required: false
        default: 'fc696046da3e703450559154d9370ca74c197f8b'
      DXC_CHECKSUM:
        type: string
        required: false
        default: '4e6f4e52989aca69739880b40b9f988357f15d10ca03284377b81f1502463ff5'
    secrets:
      G64RS_REPO_WITH_PAT:
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        type: [ Debug, Release ]
    name: ubuntu-20.04 (x64, ${{ matrix.type }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-g64r-ccache-${{ matrix.type }}-x64-${{ inputs.N64RECOMP_COMMIT }}
      - name: Prepare Build
        run: |-
          git clone ${{ secrets.G64RS_REPO_WITH_PAT }}
          cp ./Goemon64RecompSecrets/* ./
      - name: Apply Patches
        run: |
          cp ./tlb_and_controller_pak_support.patch ./lib/N64ModernRuntime
          cd ./lib/N64ModernRuntime
          git apply ./tlb_and_controller_pak_support.patch
          cd ../..
          cp ./split_rectangles.patch ./lib/rt64
          cd ./lib/rt64
          git apply ./split_rectangles.patch
          cd ../..
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libsdl2-dev libgtk-3-dev lld llvm clang-18 gcc-10 libfuse2
      - name: Build N64Recomp & RSPRecomp
        run: |
          git clone https://github.com/Mr-Wiseguy/N64Recomp.git --recurse-submodules N64RecompSource
          cd N64RecompSource
          git checkout ${{ inputs.N64RECOMP_COMMIT }}
          git submodule update --init --recursive
          
          # enable ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          
          # Build N64Recomp & RSPRecomp
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build
          cmake --build cmake-build --config Release --target N64RecompCLI -j $(nproc)
          cmake --build cmake-build --config Release --target RSPRecomp -j $(nproc)
          
          # Copy N64Recomp & RSPRecomp to root directory
          cp cmake-build/N64Recomp ..
          cp cmake-build/RSPRecomp ..
      - name: Run N64Recomp & RSPRecomp
        run: |
          ./N64Recomp mnsg.us.toml
          ./RSPRecomp aspMain.us.toml
      - name: Build GoemonRecomp
        run: |-
          # enable ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=clang++-18 -DCMAKE_C_COMPILER=clang-18 -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build -DPATCHES_C_COMPILER=clang-17  -DPATCHES_LD=ld.lld-17 -DPATCHES_OBJCOPY=llvm-objcopy-17
          cmake --build cmake-build --config ${{ matrix.type }} --target Goemon64Recompiled -j $(nproc)
      - name: Prepare Archive
        run: |
          mv cmake-build/Goemon64Recompiled Goemon64Recompiled
          rm -rf assets/scss
          tar -czf Goemon64Recompiled.tar.gz Goemon64Recompiled assets/ gamecontrollerdb.txt
      - name: Archive Goemon64Recomp
        uses: actions/upload-artifact@v4
        with:
          name: Goemon64Recompiled-${{ runner.os }}-X64-${{ matrix.type }}
          path: Goemon64Recompiled.tar.gz
      - name: Build AppImage
        run: |-
          ./.github/linux/appimage.sh 
      - name: Goemon64Recomp AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Goemon64Recompiled-AppImage-X64-${{ matrix.type }}
          path: Goemon64Recompiled-*.AppImage
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        type: [ Debug, RelWithDebInfo ]
    name: windows-2022 (${{ matrix.type }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-g64r-ccache-${{ matrix.type }}
      - name: Install Windows Dependencies
        run: |
          choco install ninja
          Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
      - name: Configure Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Prepare Build
        run: |-
          git clone ${{ secrets.G64RS_REPO_WITH_PAT }}
          Copy-Item -Path .\Goemon64RecompSecrets\* -Destination .\ -Recurse
      - name: Apply Patches
        run: |
          Copy-Item -Path .\tlb_and_controller_pak_support.patch -Destination .\lib\N64ModernRuntime
          cd .\lib\N64ModernRuntime
          git apply .\tlb_and_controller_pak_support.patch
          cd ..\..
          Copy-Item -Path .\split_rectangles.patch -Destination .\lib\rt64
          cd .\lib\rt64
          git apply .\split_rectangles.patch
          cd ..\..
      - name: Build N64Recomp & RSPRecomp
        run: |
          git clone https://github.com/Mr-Wiseguy/N64Recomp.git --recurse-submodules N64RecompSource
          cd N64RecompSource
          git checkout ${{ inputs.N64RECOMP_COMMIT }}
          git submodule update --init --recursive

          # enable ccache
          set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
          $cpuCores = (Get-CimInstance -ClassName Win32_Processor).NumberOfLogicalProcessors

          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build
          cmake --build cmake-build --config Release --target N64RecompCLI -j $cpuCores
          cmake --build cmake-build --config Release --target RSPRecomp -j $cpuCores

          # Copy N64Recomp & RSPRecomp to root directory
          cp cmake-build/N64Recomp.exe ..
          cp cmake-build/RSPRecomp.exe ..
      - name: Run N64Recomp & RSPRecomp
        run: |
          ./N64Recomp.exe mnsg.us.toml
          ./RSPRecomp.exe aspMain.us.toml
      - name: Build GoemonRecomp
        run: |-
          # enable ccache
          set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
          $cpuCores = (Get-CimInstance -ClassName Win32_Processor).NumberOfLogicalProcessors

          # remove LLVM from PATH so it doesn't overshadow the one provided by VS
          $env:PATH = ($env:PATH -split ';' | Where-Object { $_ -ne 'C:\Program Files\LLVM\bin' }) -join ';'

          cmake -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B cmake-build -DCMAKE_CXX_FLAGS="-Xclang -fexceptions -Xclang -fcxx-exceptions"
          cmake --build cmake-build --config ${{ matrix.type }} --target Goemon64Recompiled -j $cpuCores
        env:
          SDL2_VERSION: ${{ inputs.SDL2_VERSION }}
      - name: Prepare Archive
        run: |
          Move-Item -Path "cmake-build/Goemon64Recompiled.exe" -Destination "Goemon64Recompiled.exe"
          Move-Item -Path "cmake-build/dxcompiler.dll" -Destination "dxcompiler.dll"
          Move-Item -Path "cmake-build/dxil.dll" -Destination "dxil.dll"
          Move-Item -Path "cmake-build/SDL2.dll" -Destination "SDL2.dll"
          Move-Item -Path "cmake-build/Goemon64Recompiled.pdb" -Destination "Goemon64Recompiled.pdb"
          Remove-Item -Path "assets/scss" -Recurse -Force
      - name: Archive Goemon64Recomp
        uses: actions/upload-artifact@v4
        with:
          name: Goemon64Recompiled-${{ runner.os }}-${{ matrix.type }}
          path: |
            Goemon64Recompiled.exe
            dxcompiler.dll
            dxil.dll
            SDL2.dll
            assets/
            gamecontrollerdb.txt
      - name: Archive Debug Files
        uses: actions/upload-artifact@v4
        with:
          name: Goemon64Recompiled-PDB-${{ matrix.type }}
          path: |
            Goemon64Recompiled.pdb
